name: horizon_try
channels:
- conda-forge
- robostack
- francesco_ruscelli
dependencies:
- python=3.8
- scipy
- numpy
- matplotlib
- ipython
- casadi
- ros-noetic-ros-base
- ros-noetic-pinocchio
- francesco_ruscelli::casadi_kin_dyn
- francesco_ruscelli::horizon
