name: horizon_try
channels:
- conda-forge
dependencies:
- ipykernel=5.1
- jupyterlab-link-share=0.2
- python=3.8
- nbconvert=6
- nodejs=14
- jupyterlab=3.2
- ipympl
- ipyvuetify
- bqplot
- ipywidgets
- ros-noetic-ros-core
- ros-noetic-rospy
- ros-noetic-rosbridge-suite
- ros-noetic-rosbag
- ros-noetic-rosauth
- ros-noetic-tf2-web-republisher

