name: horizon_try
channels:
- conda-forge
- robostack
dependencies:
#- ipykernel=5.1
#- jupyterlab-link-share=0.2
- python=3.8
- nbconvert=6
- nodejs=14
- jupyterlab=3.2
- matplotlib
- catkin_tools
#- ipympl
#- ipyvuetify
#- bqplot
#- ipywidgets
- ros-noetic-robot-state-publisher
- ros-noetic-ros-core
- ros-noetic-rospy
#- ros-noetic-rosbridge-suite
#- ros-noetic-rosbag
#- ros-noetic-rosauth
#- ros-noetic-tf2-web-republisher
- robostack::jupyterlab-ros
- robostack::jupyter-amphion
- robostack::jupyter-ros
- pip
- pip:
  - casadi-horizon==0.0.3

