name: horizon_try
channels:
- conda-forge
- robostack
dependencies:
- python=3.6
- nodejs=14
- jupyterlab=3.2
- matplotlib
#- ipympl
#- ipyvuetify
#- bqplot
- urdfdom
#- icu
#- ipywidgets
#- ros-noetic-ros-base
#- libboost=1.71
- ros-melodic-catkin
- ros-melodic-robot-state-publisher
- ros-melodic-joint-state-publisher
- ros-melodic-ros-core
- ros-melodic-rospy
- ros-melodic-xacro
#- ros-noetic-rosbridge-suite
#- ros-noetic-rosbag
#- ros-noetic-rosauth
#- ros-noetic-tf2-web-republisher

- robostack::jupyterlab-ros
- robostack::jupyter-amphion
- robostack::jupyter-ros
#- pip
- pip:
  - casadi-horizon

