name: horizon
channels:
- conda-forge
- robostack
- francesco_ruscelli
dependencies:
- python=3.8
- nodejs=14
- jupyterlab=3.2
- matplotlib
- scipy
- numpy
- matplotlib
- ipython
- casadi
- ros-noetic-ros-base
- ros-noetic-robot-state-publisher
- ros-noetic-joint-state-publisher
- ros-noetic-pinocchio
- francesco_ruscelli::casadi_kin_dyn
- francesco_ruscelli::horizon=0.4.5
- robostack::jupyterlab-ros
