name: horizon_try
channels:
- conda-forge
- robostack
dependencies:
- python=3.8
- nodejs=14
- jupyterlab=3.2
- matplotlib
#- ipympl
#- ipyvuetify
#- bqplot
- urdfdom_headers
- libboost
- icu
#- ipywidgets
- ros-noetic-catkin
- ros-noetic-robot-state-publisher
- ros-noetic-joint-state-publisher
- ros-noetic-ros-core
- ros-noetic-rospy
- ros-noetic-xacro
#- ros-noetic-rosbridge-suite
#- ros-noetic-rosbag
#- ros-noetic-rosauth
#- ros-noetic-tf2-web-republisher

- robostack::jupyterlab-ros
- robostack::jupyter-amphion
- robostack::jupyter-ros
- pip
- pip:
  - casadi-horizon

