#!/bin/bash

mkdir -p ~/horizon_ws/src
cd ~/horizon_ws/

conda init
conda run -n notebook
conda env list

catkin_make

echo source ~/horizon_ws/devel/setup.bash >> ~/.bashrc

#cd src/
#git clone https://github.com/FrancescoRuscelli/spot-ros-pkg
